//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AOI.rc
//
#define IDCANCEL2                       3
#define IDD_ABOUTBOX                    100
#define IDD_MYTREEVIEW                  103
#define IDD_ROOTVIEW                    104
#define IDD_PROGRAMVIEW                 105
#define IDD_MAINVIEW                    107
#define IDD_PCBINFODLG                  108
#define IDD_GRAPHVIEW                   109
#define IDR_MAINFRAME                   128
#define IDR_AOITYPE                     129
#define IDR_MAINFRAME1                  129
#define IDS_TREEROOTNAME_E              130
#define IDR_MAINFRAME2                  130
#define IDR_MAINFRAME_E                 130
#define IDS_TREEROOTNAME_C              131
#define IDD_COMMANDDLG                  131
#define IDD_PROGRAMINFODLG              132
#define IDD_DETECTINFODLG               133
#define IDD_BIGGRAPHVIEW                134
#define IDD_SMALLGRAPHVIEW              135
#define IDD_FACTIMAGE                   136
#define IDD_FOVINFODLG                  137
#define IDD_DATUMMARKINFODLG            138
#define IDD_ORGANINFODLG                139
#define IDC_TRCKWE                      139
#define IDC_HANDOPEN                    140
#define IDD_PRGSTEP                     140
#define IDC_HANDHOLD                    141
#define IDD_COORDCALC                   141
#define IDD_ORGANINFODLG1               142
#define IDD_ORGANSELECT                 142
#define IDC_TRCKNESW                    143
#define IDD_ORGANPRG                    143
#define IDC_TRCKNS                      144
#define IDD_ORGANPRGSTEP                144
#define IDC_TRCKNWSE                    145
#define IDD_FOOTPRG                     145
#define IDC_TRACKMOVE                   146
#define IDD_NEXTPAD                     146
#define IDC_COPYWAY                     147
#define IDD_BIGGRAPHVIEW1               147
#define IDD_DETECTBIGGRAPHVIEW          147
#define IDD_DETECTSMALLVIEW             148
#define IDD_DETECTCMDDLG                149
#define IDD_DETECTMAINVIEW              150
#define IDD_TEMPLATESELECT              151
#define IDD_WORKSURE                    152
#define IDD_OBJIMAGE                    153
#define IDI_ICON1                       153
#define IDD_ORGANIMAGE                  154
#define IDD_BARPRGGUID                  155
#define IDD_BARPRGGUID1                 156
#define IDD_SPELLPRGGUID                156
#define IDD_VALIDATEERR                 157
#define IDD_DETECTORGANINFO             158
#define IDD_DETECTERRDATAINF            159
#define IDD_REPORTVIEW                  160
#define IDD_REPORTSTAT                  161
#define IDD_USERMGR                     162
#define IDD_USEREDIT                    163
#define IDD_LOGIN                       164
#define IDI_ICON2                       164
#define IDR_ORGAN_POP                   165
#define IDR_FOV_POP                     166
#define IDR_ORGAN_POP1                  167
#define IDR_MARK_POP                    167
#define IDD_DIALOG1                     168
#define IDD_WAIT                        168
#define IDR_AOITYPE_E                   168
#define IDD_FOVINFODLG1                 169
#define IDD_SPELLINFODLG                169
#define IDR_MAINFRAME3                  169
#define IDR_ORGAN_POP_E                 169
#define IDD_BARINFODLG                  170
#define IDR_FOV_POP_E                   170
#define IDD_SETCOLORDLG                 171
#define IDR_MARK_POP_E                  171
#define IDD_ORGANEDIT                   172
#define IDD_MARKPRGGUID                 173
#define IDD_DETECTBASEINFO              174
#define IDD_DIALOG2                     175
#define IDD_SET_CAMERA                  175
#define IDD_SYSTEM_CFG                  176
#define IDD_MOTOR_CTRL                  177
#define IDD_WAIT1                       178
#define IDD_WAIT_LOADPCB                178
#define IDD_SPELLPRGGUID1               179
#define IDD_ANGLEOFFSETPRGGUID          179
#define IDC_TREEMENU                    1000
#define IDC_SHOWBITMAP                  1002
#define IDC_BUTTON1                     1003
#define IDC_QUERY                       1003
#define IDC_PCBNAME                     1004
#define IDC_CENTERYD                    1004
#define IDC_WIDTH                       1005
#define IDC_TAB1                        1005
#define IDC_CENTERYAA                   1005
#define IDC_HEIGHT                      1006
#define IDC_EDITAREA                    1006
#define IDC_CENTERYA                    1006
#define IDC_CREATEMARK                  1007
#define IDC_CENTERXAA                   1007
#define IDC_LASTPRGTIME                 1007
#define IDC_FOVLIST                     1008
#define IDC_CENTERXA                    1008
#define IDC_LASTPRGSTEP                 1008
#define IDC_CENTERXDD                   1009
#define IDC_FOVNUM                      1009
#define IDC_CENTERXD                    1010
#define IDC_ORGANNUM                    1010
#define IDC_CENTERWAA                   1011
#define IDC_LASTPRGSTEP4                1011
#define IDC_MARKNUM                     1011
#define IDC_CENTERWA                    1012
#define IDC_STARTID                     1012
#define IDC_JIAODU_X                    1012
#define IDC_NEW                         1013
#define IDC_CENTERWDD                   1013
#define IDC_JIAODU_Y                    1013
#define IDC_MODIFY                      1014
#define IDC_CENTERWD                    1014
#define IDC_DELETE                      1015
#define IDC_CENTERHAA                   1015
#define IDC_DATUMMARKLIST               1016
#define IDC_IMPORT                      1016
#define IDC_CENTERHA                    1016
#define IDC_SCANDFOV                    1016
#define IDC_ORGANLIST                   1017
#define IDC_SHOWIMAGE                   1017
#define IDC_CENTERHDD                   1017
#define IDC_CALCRELATIVE                1018
#define IDC_OK                          1018
#define IDC_CENTERHD                    1018
#define IDC_NEXT                        1019
#define IDC_IMPORT2                     1019
#define IDC_DELPRG                      1019
#define IDC_CANCLE                      1020
#define IDC_CLOSE                       1020
#define IDC_INFO                        1021
#define IDC_NEXT2                       1021
#define IDC_CLOSE2                      1021
#define IDC_LEARN                       1021
#define IDC_COMBO1                      1022
#define IDC_ERRORTYPE                   1022
#define IDC_STATTYPE                    1022
#define IDC_ISPOLAR                     1022
#define IDC_TEMPTYPE                    1022
#define IDC_CAM_MODE                    1022
#define IDC_AXIS                        1022
#define IDC_PCB_ENTRY                   1022
#define IDC_SELCTIORGAN1                1023
#define IDC_DO_WAY                      1023
#define IDC_TESTER                      1023
#define IDC_IMAGTYPE                    1023
#define IDC_CAM_SNAP_MODE               1023
#define IDC_ORGANNAME1                  1024
#define IDC_RELATIVE                    1024
#define IDC_CAM_TRIG_POLARITY           1024
#define IDC_CADX                        1025
#define IDC_CAM_STROBE_POLARITY2        1025
#define IDC_CADY                        1026
#define IDC_CAM_ADC_BITS                1026
#define IDC_CURRENTX                    1027
#define IDC_SHUTER_UNIT                 1027
#define IDC_CURRENTY                    1028
#define IDC_PROGRAM                     1028
#define IDC_SELCTIORGAN2                1029
#define IDC_FOOTPRINT                   1029
#define IDC_DETECT                      1029
#define IDC_ORGANNAME2                  1030
#define IDC_SKIP                        1030
#define IDC_REPORT                      1030
#define IDC_CADX2                       1031
#define IDC_INVALID                     1031
#define IDC_SYSTEM                      1031
#define IDC_CADY2                       1032
#define IDC_ORGANNAME                   1032
#define IDC_CURRENTX2                   1033
#define IDC_STAT                        1033
#define IDC_KINDRED_VALUE               1033
#define IDC_CURRENTY2                   1034
#define IDC_CURRENTY3                   1034
#define IDC_LIMIT_VALUE                 1034
#define IDC_ORGANNAME3                  1035
#define IDC_RELATIVEVALUE               1035
#define IDC_TURE                        1035
#define IDC_TURN                        1035
#define IDC_SPELL_NO                    1035
#define IDC_SPINX                       1036
#define IDC_SPINX2                      1037
#define IDC_SPINY                       1037
#define IDC_FOOTNUM_ADD                 1037
#define IDC_FOOTNUM_DOWN                1038
#define IDC_FRONT                       1038
#define IDC_SPACE_ADD_M                 1039
#define IDC_LEFT                        1039
#define IDC_SPACE_ADD                   1040
#define IDC_RIGHT                       1040
#define IDC_CHECK1                      1041
#define IDC_OKANDNEW                    1041
#define IDC_DATE_CHECK                  1041
#define IDC_ASKWHENERR                  1041
#define IDC_NEED_DETECT                 1041
#define IDC_CAM_ENABLE_MONITOR          1041
#define IDC_SPACE_DOWN                  1042
#define IDC_BEGINDETECT                 1042
#define IDC_MANUAL                      1042
#define IDC_TIME_CHECK                  1042
#define IDC_MANUALTYPE                  1042
#define IDC_CAM_BLKLEVEL_CAL            1042
#define IDC_SPACE_DOWN_M                1043
#define IDC_TEMPLATELIST                1043
#define IDC_AUTO                        1043
#define IDC_EXCORDER                    1044
#define IDC_STOP                        1044
#define IDC_PRE                         1045
#define IDC_DETECT_ORGAN                1045
#define IDC_IMAGE                       1046
#define IDC_CENTERX                     1047
#define IDC_CENTERW                     1048
#define IDC_CENTERY                     1049
#define IDC_CENTERH                     1050
#define IDC_CENTERYDD                   1051
#define IDC_STATUS                      1052
#define IDC_MOUSEINFO                   1053
#define IDC_TEMPLATEIMG                 1056
#define IDC_CURRENT_IMG                 1057
#define IDC_ERRDATALIST                 1060
#define IDC_STAR_DATE                   1062
#define IDC_END_DATE                    1063
#define IDC_STAR_TIME                   1064
#define IDC_END_TIME                    1065
#define IDC_ERRCOUNT                    1066
#define IDC_START_ID                    1067
#define IDC_END_ID                      1068
#define IDC_START_BARNO                 1069
#define IDC_ENDBARNO                    1070
#define IDS_ID_S                        1071
#define IDC_MASTERLIST                  1072
#define IDC_DETAILLIST                  1073
#define IDC_ETYPESTATLIST               1073
#define IDC_ORGANSTATLIST               1074
#define IDC_ORGANTOTAL                  1075
#define IDC_ERRTOTAL                    1076
#define IDC_SHOWEREA                    1077
#define IDC_USERLIST                    1078
#define IDC_CANCEL                      1079
#define IDC_USERNAME                    1080
#define IDC_CANCEL2                     1080
#define IDC_DEFAULT                     1080
#define IDC_PASSWARD                    1081
#define IDC_EDIT1                       1081
#define IDC_LIMIT                       1081
#define IDC_S_CENTERX                   1081
#define IDC_FOOTNUM                     1081
#define IDC_EXPOSURE                    1081
#define IDC_IMAGE_NUM                   1081
#define IDC_CONFIRM                     1082
#define IDC_SURE                        1082
#define IDC_S_CENTERY                   1082
#define IDC_SHUTER_SPEED                1082
#define IDC_SPELLLIST                   1083
#define IDC_S_WIDTH                     1083
#define IDC_MIDY                        1083
#define IDC_S_HEIGHT                    1084
#define IDC_COLOR_EDITA                 1084
#define IDC_PADY                        1084
#define IDC_B_CENTERX                   1085
#define IDC_COLOR_FOV                   1085
#define IDC_B_CENTERY                   1086
#define IDC_COLOR_MARK                  1086
#define IDC_B_WIDTH                     1087
#define IDC_COLOR_ORGAN                 1087
#define IDC_EDIT8                       1088
#define IDC_B_HEIGHT                    1088
#define IDC_COLOR_BARCODE               1088
#define IDS_SAVE                        1089
#define IDC_SAVE                        1089
#define IDC_NAME                        1090
#define IDC_MIDX                        1091
#define IDC_PADX                        1092
#define IDC_CURRENT_ID                  1092
#define IDC_CURRENT_BARCODE             1093
#define IDC_DET_PCBNUM                  1094
#define IDC_ERR_PCBNUM                  1095
#define IDC_DET_ORGANNUM                1096
#define IDC_ERR_ORGANNUM                1097
#define IDC_STARTTIME                   1098
#define IDC_HOR_BLANK                   1099
#define IDC_VER_BLANK                   1100
#define IDC_NORMAL_SPEED                1101
#define IDC_HIGH_SPEED2                 1102
#define IDC_HIGH_SPEED                  1102
#define IDC_BLKLEVEL_CAL_RED            1103
#define IDC_BLKLEVEL_CAL_GREEN1         1104
#define IDC_BLKLEVEL_CAL_GREEN2         1105
#define IDC_BLKLEVEL_CAL_BLUE           1106
#define IDC_CAM_BRIGHTNESS              1107
#define IDC_GAIN_RED                    1108
#define IDC_GAIN_GREEN1                 1109
#define IDC_GAIN_GREEN2                 1110
#define IDC_GAIN_BLUE                   1111
#define IDC_GAIN_CAMERA                 1112
#define IDC_HOR_BLANK_VAL               1113
#define IDC_VER_BLANK_VAL               1114
#define IDC_MOTOR_STEP                  1114
#define IDC_BLKLEV_CAL_RED_VAL          1115
#define IDC_PELS_MM                     1115
#define IDC_BLKLEV_CAL_GREEN1_VAL       1116
#define IDC_GOHOME                      1116
#define IDC_PELS_MM2                    1116
#define IDC_TRACK_MINWIDTH              1116
#define IDC_BLKLEV_CAL_GREEN2_VAL       1117
#define IDC_MOVE                        1117
#define IDC_PCB_IN_TIME                 1117
#define IDC_BLKLEV_CAL_BLUE_VAL2        1118
#define IDC_POS                         1118
#define IDC_PCB_OUT_TIME                1118
#define IDC_BRIGHTNESS_VAL              1119
#define IDC_MOTOR_SPEED                 1119
#define IDC_GAIN_RED_VAL                1120
#define IDC_MOTOR_MOVOFFSET_X           1120
#define IDC_GAIN_GREEN1_VAL             1121
#define IDC_MOTOR_MOVOFFSET_Y           1121
#define IDC_GAIN_GREEN2_VAL             1122
#define IDC_MOTOR_MOVOFFSET_Y2          1122
#define IDC_ZHOU_JIAODU_OFFSET          1122
#define IDC_GAIN_BLUE_VAL               1123
#define IDC_GAIN_RED_VAL5               1124
#define IDC_GAIN_CAMERA_VAL             1124
#define ID_PREVIEW_                     32771
#define ID_PREVIEW_SCAN                 32772
#define ID_SHOW_FULL                    32773
#define ID_ADJUST                       32774
#define ID_COLLECT                      32775
#define ID_ZOOM_IN                      32776
#define ID_ZOOM_OUT                     32777
#define ID                              32778
#define ID_ORIGINAL                     32779
#define ID_NEW_TEMPLATE                 32780
#define ID_OPEN_TEMPLATE                32781
#define ID_SAVE_TEMPLATE                32782
#define ID_ZOOMIN                       32783
#define ID_ZOOMOUT                      32784
#define ID_PRG_GUID                     32785
#define ID_PRG_GUIDE                    32786
#define ID_32787                        32787
#define ID_PRG_                         32788
#define ID_PRG_SCANPCB                  32789
#define ID_PRG_EDITAREA                 32790
#define ID_PRG_MARK                     32791
#define ID_PRG_EDITFOV                  32792
#define ID_32793                        32793
#define ID_32794                        32794
#define ID_32795                        32795
#define ID_32796                        32796
#define ID_PRG_SCANFOV                  32797
#define ID_PRG_IMPORTCAD                32798
#define ID_PRG_COORDSCALE               32799
#define ID_PRG_ORGAN                    32800
#define ID_32801                        32801
#define ID_PRG_SP                       32802
#define ID_PRG_SPELLPCB                 32803
#define ID_PRG_BARCODE                  32804
#define ID_PRG                          32805
#define ID_PRG_ADDFOV                   32806
#define ID_T_MANUAL                     32807
#define ID_T_AUTO                       32808
#define ID_T_STOP                       32809
#define ID_T_INPUTPCB                   32810
#define ID_T_OUTPUTPCB                  32811
#define ID_T_                           32812
#define ID_T_CLARMP                     32813
#define ID_T_XTOORIGIN                  32814
#define ID_T_YTOORIGIN                  32815
#define ID_T_PCBUP                      32816
#define ID_T_PCBDOWN                    32817
#define ID_T_OR                         32818
#define ID_T_ORGAN                      32819
#define ID_                             32820
#define ID_T_LOOSENPCB                  32821
#define ID_T_ACCEPTPCB                  32822
#define ID_T_ORIGINX                    32823
#define ID_T_ORIGINY                    32824
#define ID_T_SENDPCB                    32825
#define ID_32826                        32826
#define ID_CAMAL                        32827
#define ID_CAMER                        32828
#define ID_CAMERA_SET                   32829
#define ID_REMOVE_SET                   32830
#define ID_SYSTEM_SET                   32831
#define ID_USER_MGR                     32832
#define ID_USRMGR                       32833
#define ID_BUTTON32835                  32835
#define ID_BUTTON32836                  32836
#define ID_BUTTON32837                  32837
#define ID_BUTTON32838                  32838
#define ID_BUTTON32841                  32841
#define ID_BUTTON32842                  32842
#define ID_ORGANPOP_32843               32843
#define ID_ORGANPOP_32844               32844
#define ID_ORGANPOP_32845               32845
#define ID_LOGIN                        32846
#define ID_LOGOUT                       32847
#define ID_FILE_LOGOUT                  32848
#define ID_Menu                         32849
#define ID_SYSTEM                       32850
#define ID_32851                        32851
#define ID_SETCOLOR                     32852
#define ID_SETTING_DISPLAYCOLOR         32853
#define ID_ORGANPOP_32854               32854
#define ID_ORGANPOP_32855               32855
#define ID_32856                        32856
#define ID_DELTEMPLATE                  32857
#define ID_FILE_DELTEMPLATE             32858
#define ID_32859                        32859
#define ID_32860                        32860
#define ID_LIGHT_ON                     32861
#define ID_LIGHT_OFF                    32862
#define ID_OPERATION_                   32863
#define ID_SHOWIMAGE                    32864
#define ID_SHOWMARKIMAGE                32865
#define ID_32866                        32866
#define ID_AN                           32867
#define ID_ANGLE_OFFSET                 32868
#define ID_PROGRAM_ANGLEOFFSET          32869
#define ID_PRG_ANGLEOFFSET              32870
#define ID_32871                        32871

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32872
#define _APS_NEXT_CONTROL_VALUE         1119
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
